# Dockerfile for Development

# Use an official Node.js runtime as a parent image
FROM node:24

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
 && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies using npm
RUN npm install

# Copy the rest of the application's source code
COPY . .

# Expose port 3000 for the Next.js development server
EXPOSE 3000

# Command to run the development server
CMD ["npm", "run", "dev"]
